font_family      Input Mono Narrow
font_size        14.0

cursor_shape     block
cursor		#B0DCE8 
shell_integration no-cursor

background       #090D12
foreground       #B3F9F5

selection_foreground #B3F9F5
selection_background #2E4D53

active_tab_background       #0F1A20
active_tab_foreground       #B0DCE8
inactive_tab_background     #0A1216
inactive_tab_foreground     #4A6575

background_opacity     0.75
background_blur        64 
transparent_background_colors #0A1418@0.4 #0A1317@0.5 #0A1620@0.6 
active_border_color #070D10
inactive_border_color #0A1216
hide_window_decorations titlebar-only
window_padding_width   10

window_decorations       resize

confirm_os_window_close -1

initial_rows 80
initial_columns 100

# Keybindings ported from wezterm
# Shift+Enter sends newline (like wezterm)
map shift+enter send_text all \n

# Close current pane
map cmd+w close_window

