-- DAP debug configurations for C++/JUCE
-- SSOT for debug configuration management
-- No project-type concept: a project is whatever formats its build produces
-- (detectAvailableFormats below). What to attach to, and whether a DAW is
-- involved, is decided entirely by the resolved format — never by classifying
-- the project itself.
local M = {}

-- ============================================================================
-- CONFIG FILE MANAGEMENT (SSOT)
-- ============================================================================

local function getConfigFilePath()
  return vim.fn.getcwd() .. '/.nvim-dap-config'
end

-- Load .nvim-dap-config as Lua table
-- FAIL FAST = FAIL? FAST FIX!
-- Any problem → IMMEDIATELY show dialog and let user fix
-- Returns config if valid, shows dialog and returns result if invalid
function M.loadDawConfig(callback)
  local configFile = getConfigFilePath()
  
  -- File doesn't exist → show dialog immediately
  if vim.fn.filereadable(configFile) ~= 1 then
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- File exists but has invalid Lua syntax → delete and show dialog immediately
  local ok, config = pcall(dofile, configFile)
  if not ok then
    vim.notify('DAP config corrupted. Reconfiguring...')
    vim.fn.delete(configFile)
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- Config returned nil → delete and show dialog immediately
  if not config then
    vim.notify('DAP config empty. Reconfiguring...')
    vim.fn.delete(configFile)
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- Missing format field → show dialog immediately
  if not config.format or config.format == '' then
    vim.notify('DAP config missing format. Reconfiguring...')
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- Standalone has no DAW pairing — daw/dawPath checks don't apply
  if config.format == 'Standalone' then
    return config
  end

  -- Missing daw field → show dialog immediately
  if not config.daw or config.daw == '' then
    vim.notify('DAP config missing daw. Reconfiguring...')
    M.showDawFormatDialog(callback)
    return nil
  end

  -- Missing dawPath field → show dialog immediately
  if not config.dawPath or config.dawPath == '' then
    vim.notify('DAP config missing dawPath. Reconfiguring...')
    M.showDawFormatDialog(callback)
    return nil
  end

  -- Invalid dawPath → show dialog immediately
  if vim.fn.filereadable(config.dawPath) ~= 1 then
    vim.notify('DAP config dawPath invalid: ' .. config.dawPath .. '. Reconfiguring...')
    M.showDawFormatDialog(callback)
    return nil
  end

  return config
end

-- Save .nvim-dap-config as Lua table (self-documented)
-- Only fails if write fails (disk full, permissions) - beyond our control
-- scheme defaults to 'Debug' when omitted (showDawFormatDialog's initial
-- save predates scheme tracking and has no build behind it yet).
function M.saveDawConfig(format, daw, dawPath, scheme)
  local configFile = getConfigFilePath()
  local content = string.format(
    '-- DAP Debug Configuration\n' ..
    '-- Generated by Neovim DAP\n' ..
    'return {\n' ..
    '  format = "%s",        -- Plugin format (framework-dependent, see detectAvailableFormats)\n' ..
    '  daw = "%s",           -- DAW name (for display/killall)\n' ..
    '  dawPath = "%s",       -- Absolute path to DAW executable\n' ..
    '  scheme = "%s",        -- Debug or Release, last written by buildDebugAndRun/buildReleaseAndRun\n' ..
    '}',
    format,
    daw,
    dawPath,
    scheme or 'Debug'
  )

  local ok, err = pcall(vim.fn.writefile, vim.split(content, '\n'), configFile)
  if not ok then
    vim.notify('Failed to write DAP config (disk/permissions issue): ' .. tostring(err))
    return false
  end

  return true
end

-- Persists scheme (Debug/Release) into the existing SSOT config ahead of
-- build+launch — runBuildAndLaunch calls this before buildFormat so every
-- program() closure below resolves the artefact for the scheme this
-- invocation actually requested, not whichever is newest on disk.
--
-- Reads the file directly rather than through loadDawConfig: on a fresh
-- project with no .nvim-dap-config yet, loadDawConfig's missing/invalid
-- branches show the format dialog as a side effect, which would race
-- buildFormat's own loadDawConfig call immediately after. No config yet
-- means no scheme to persist — buildFormat's dialog handles first-time
-- setup on its own.
function M.setScheme(scheme)
  local configFile = getConfigFilePath()
  if vim.fn.filereadable(configFile) ~= 1 then
    return false
  end
  local ok, config = pcall(dofile, configFile)
  if not ok or not config or not config.format then
    return false
  end
  return M.saveDawConfig(config.format, config.daw, config.dawPath, scheme)
end

-- Known JUCE/clap-juce-extensions plugin format target suffixes.
-- Same vocabulary build-debug.sh already matches against (script line ~38).
local KNOWN_PLUGIN_FORMATS = {
  VST3 = true, AU = true, AAX = true, AUv3 = true,
  Unity = true, VST = true, Standalone = true, CLAP = true,
}

-- AppBuilder.cmake's pure-app target (_App suffix) means the same thing as
-- PluginBuilder.cmake's _Standalone target: launch the binary directly, no
-- DAW pairing. build-debug.sh already treats them identically (FORMAT=
-- "Standalone" falls back to any bare non-format target — script line 38),
-- so both are surfaced under the single 'Standalone' format label here.
local FORMAT_ALIAS = { App = 'Standalone' }

-- Read the real FORMATS list straight out of the framework's PluginBuilder.cmake
-- — text only, no cmake process, so this can never surface a configure/build
-- error. Only resolves for frameworks whose PluginBuilder.cmake FORMATS line
-- is literal tokens (e.g. jam/cmake/PluginBuilder.cmake:407, 'FORMATS VST3
-- AU Standalone'). KANJUT's (kuassa/___lib___/cmake/PluginBuilder.cmake:154)
-- forwards a variable — 'FORMATS ${PARAMS_FORMATS}' — so this returns nil for
-- kuassa projects and detectFormatsFromMetadata below is tried instead.
local function detectFormatsFromPluginBuilder(root)
  local cmakeFile = root .. '/CMakeLists.txt'
  if vim.fn.filereadable(cmakeFile) ~= 1 then
    return nil
  end

  local content = table.concat(vim.fn.readfile(cmakeFile), '\n')
  local modulesPath = content:match('set%(FRAMEWORK_MODULES_PATH%s+"([^"]+)"')
  if not modulesPath then
    return nil
  end

  local pluginBuilderFile = root .. '/../' .. modulesPath .. '/cmake/PluginBuilder.cmake'
  if vim.fn.filereadable(pluginBuilderFile) ~= 1 then
    return nil
  end

  local builderContent = table.concat(vim.fn.readfile(pluginBuilderFile), '\n')
  -- Capture the rest of the FORMATS line only — the file's next line is
  -- VST3_CATEGORIES/AAX_CATEGORY etc. (kuassa/___lib___/cmake/PluginBuilder.cmake:155-156),
  -- which must not bleed into this token scan.
  local formatsLine = builderContent:match('FORMATS%s+([^\r\n]*)')
  if not formatsLine then
    return nil
  end

  -- AU is Apple-only (JUCE itself won't produce it on Windows) — a platform
  -- fact, not project-specific data, so filtering it here isn't hardcoding
  -- a format list. Tokens matched against KNOWN_PLUGIN_FORMATS (not a bare
  -- uppercase character class) so names with digits/lowercase (VST3, AUv3,
  -- Standalone) are captured correctly.
  local is_windows = vim.fn.has('win32') == 1
  local formats, seen = {}, {}
  for token in formatsLine:gmatch('%a[%a%d]*') do
    local fmt = FORMAT_ALIAS[token] or token
    if KNOWN_PLUGIN_FORMATS[fmt] and not (fmt == 'AU' and is_windows) and not seen[fmt] then
      seen[fmt] = true
      table.insert(formats, fmt)
    end
  end

  return #formats > 0 and formats or nil
end

-- KANJUT-framework projects declare formats as data, not CMake text: the
-- project's own Source/layout/metadata.md 'formats' row (e.g.
-- jreng-filter-strip/Source/layout/metadata.md:16, 'formats | VST VST3 AU
-- AAX Standalone') is parsed at configure time into PARAMS_FORMATS by
-- Metadata.cmake:3-15 (table_parse against that same file, field
-- 'formats=PARAMS_FORMATS') before being forwarded through
-- PluginBuilder.cmake's FORMATS argument. Read directly — same text-only,
-- zero-subprocess contract as detectFormatsFromPluginBuilder above.
local function detectFormatsFromMetadata(root)
  local metadataFile = root .. '/Source/layout/metadata.md'
  if vim.fn.filereadable(metadataFile) ~= 1 then
    return nil
  end

  local is_windows = vim.fn.has('win32') == 1
  for _, line in ipairs(vim.fn.readfile(metadataFile)) do
    local cell = line:match('^|%s*formats%s*|%s*([^|]-)%s*|')
    if cell then
      local formats, seen = {}, {}
      for token in cell:gmatch('%a[%a%d]*') do
        local fmt = FORMAT_ALIAS[token] or token
        if KNOWN_PLUGIN_FORMATS[fmt] and not (fmt == 'AU' and is_windows) and not seen[fmt] then
          seen[fmt] = true
          table.insert(formats, fmt)
        end
      end
      return #formats > 0 and formats or nil
    end
  end

  return nil
end

-- A pure-app project declares its target with AppBuilder.cmake's _App
-- suffix straight in its own CMakeLists.txt (e.g. end/CMakeLists.txt:82,
-- 'TARGET_NAME END_App') — the only format such a build produces is the
-- bare binary, surfaced as 'Standalone' (see FORMAT_ALIAS).
local function detectAppTarget(root)
  local cmakeFile = root .. '/CMakeLists.txt'
  if vim.fn.filereadable(cmakeFile) ~= 1 then
    return nil
  end
  local content = table.concat(vim.fn.readfile(cmakeFile), '\n')
  if content:match('TARGET_NAME%s+"?[%w_]+_App') then
    return { 'Standalone' }
  end
  return nil
end

-- Derive buildable formats — text-only, synchronous, zero subprocess.
-- CMake is never invoked here: the picker only stores configuration
-- (.nvim-dap-config); configure/build runs later inside
-- build-debug.{bat,sh}, driven by the stored format. A project resolving
-- none of _App target, framework PluginBuilder.cmake FORMATS line, or
-- Source/layout/metadata.md 'formats' row is reported as an error — no
-- live cmake enumeration.
function M.detectAvailableFormats(callback)
  local root = vim.fn.getcwd()
  local formats = detectAppTarget(root) or detectFormatsFromPluginBuilder(root) or detectFormatsFromMetadata(root)
  if not formats then
    vim.notify(
      'Cannot determine formats: no _App target, PluginBuilder FORMATS, or metadata.md formats row resolvable for ' .. root,
      vim.log.levels.ERROR
    )
    return
  end
  callback(formats)
end

-- Show dialog to configure format, DAW, and build scheme
-- User must provide all fields (validation happens in dialog)
-- Single detected format (e.g. a pure-app project's only 'Standalone') skips
-- the picker entirely — nothing to choose, same as the format having been
-- auto-selected.
function M.showDawFormatDialog(callback)
  local is_windows = vim.fn.has('win32') == 1

  local function onFormatChosen(format)
    if not format then
      vim.notify('DAP config cancelled')
      return
    end

    -- Standalone has no DAW to pair with — save and return immediately
    if format == 'Standalone' then
      local ok = M.saveDawConfig('Standalone', '', '')
      if not ok then
        return
      end
      vim.notify('DAP config saved: Standalone')
      if callback then
        callback({ format = 'Standalone', daw = '', dawPath = '' })
      end
      return
    end

    -- Find DAW executables (OS-specific)
    local apps = {}
    if is_windows then
      -- Use vim.fn.glob — works natively in nvim without shell dependency
      local patterns = {
        'C:/Program Files/*/*.exe',
        'C:/Program Files/*/*/*.exe',
        'C:/Program Files (x86)/*/*.exe',
        'C:/Program Files (x86)/*/*/*.exe',
      }
      for _, pattern in ipairs(patterns) do
        local matches = vim.fn.glob(pattern, false, true)
        for _, path in ipairs(matches) do
          path = path:gsub('\\', '/')
          table.insert(apps, { text = path, file = path })
        end
      end
    else
      local handle = io.popen('find "/Applications" -maxdepth 2 -name "*.app" -type d 2>/dev/null')
      if handle then
        for line in handle:lines() do
          table.insert(apps, { text = line, file = line })
        end
        handle:close()
      end
    end

    if #apps == 0 then
      vim.notify('No applications found')
      return
    end

    Snacks.picker({
      items = apps,
      prompt = 'Select DAW Application: ',
      format = 'file',
      confirm = function(picker, item)
        if not item or not item.file then
          vim.notify('DAP config cancelled: No DAW selected')
          picker:close()
          return
        end

        local dawPath = item.file

        -- macOS: unwrap .app bundle to executable
        if not is_windows and dawPath:match('%.app/?$') then
          local appName = vim.fn.fnamemodify(dawPath, ':t:r')
          dawPath = dawPath:gsub('/$', '') .. '/Contents/MacOS/' .. appName
        end

        -- Verify path exists
        if vim.fn.filereadable(dawPath) ~= 1 then
          vim.notify('DAW executable not found: ' .. dawPath .. '. Try again.')
          picker:close()
          vim.defer_fn(function() M.showDawFormatDialog(callback) end, 100)
          return
        end

        -- Extract DAW name from path
        local daw = vim.fn.fnamemodify(dawPath, ':t')

        -- Save config
        local ok = M.saveDawConfig(format, daw, dawPath)
        if not ok then
          picker:close()
          return
        end

        vim.notify(string.format('DAP config saved: %s + %s', format, daw))

        if callback then
          callback({ format = format, daw = daw, dawPath = dawPath })
        end

        picker:close()
      end,
    })
  end

  M.detectAvailableFormats(function(formats)
    if #formats == 1 then
      onFormatChosen(formats[1])
      return
    end

    vim.ui.select(formats, { prompt = 'Select plugin format:' }, onFormatChosen)
  end)
end

-- Debug and Release live in separate scheme-keyed build dirs (core/build.lua's
-- BUILD_DIR) and both can exist on disk simultaneously. Every pattern list
-- below carries one Debug entry and one Release entry per platform variant,
-- so filtering to the SSOT scheme (M.setScheme, written by
-- buildDebugAndRun/buildReleaseAndRun before launch) before globbing keeps
-- newestArtefact's mtime comparison scoped to same-scheme candidates only —
-- it never crosses Debug/Release.
local function filterPatternsByScheme(patterns, scheme)
  local filtered = {}
  for _, pattern in ipairs(patterns) do
    if pattern:find('/' .. scheme .. '/', 1, true) then
      table.insert(filtered, pattern)
    end
  end
  return filtered
end

-- Returns the most recently built artefact matching any of patterns —
-- a tie-breaker among same-scheme platform variants (patterns is expected
-- pre-filtered by filterPatternsByScheme).
local function newestArtefact(patterns)
  local newest, newestTime = nil, -1
  for _, pattern in ipairs(patterns) do
    for _, match in ipairs(vim.fn.glob(pattern, false, true)) do
      local mtime = vim.fn.getftime(match)
      if mtime > newestTime then
        newest, newestTime = match, mtime
      end
    end
  end
  return newest
end

-- ============================================================================
-- DAP CONFIGURATIONS
-- ============================================================================

-- Helper to get DAW PID from config. Only valid for DAW-paired formats —
-- the loaded config's own daw field is the SSOT (Standalone/App formats
-- are saved with daw = '', per showDawFormatDialog's onFormatChosen).
local function getDawPid()
  local config = M.loadDawConfig()
  if not config then
    return nil
  end

  if not config.daw or config.daw == '' then
    error('This DAP config has no DAW pairing (' .. tostring(config.format) .. ' format). Use "Launch Standalone" instead.')
  end

  local is_windows = vim.fn.has('win32') == 1
  local handle
  if is_windows then
    -- Windows: use tasklist to find PID
    local dawName = vim.fn.fnamemodify(config.daw, ':t:r') -- strip .exe if present
    handle = io.popen('tasklist /FI "IMAGENAME eq ' .. dawName .. '.exe" /FO CSV /NH 2>nul')
  else
    handle = io.popen("pgrep -x '" .. config.daw .. "' 2>/dev/null | head -1")
  end

  if not handle then
    error('Failed to search for DAW process: ' .. config.daw)
  end

  local output = handle:read('*l')
  handle:close()

  if is_windows then
    -- tasklist CSV format: "process.exe","PID","session","session#","mem"
    local pid = output and output:match('"[^"]+","(%d+)"')
    if pid and tonumber(pid) then
      return tonumber(pid)
    end
  else
    if output and tonumber(output) then
      return tonumber(output)
    end
  end

  error('DAW not running: ' .. config.daw .. '. Launch it first.')
end

function M.setup()
  local dap = require('dap')

  local is_windows = vim.fn.has('win32') == 1

  -- whatdbg on all platforms — standalone launch + DAW attach.
  local standalone_adapter = 'whatdbg'
  local plugin_adapter = 'whatdbg'

  dap.configurations.cpp = {
    {
      name = 'Launch Standalone',
      type = standalone_adapter,
      request = 'launch',
      program = function()
        local root = vim.fn.getcwd()
        -- JUCE standalone apps are in *_App_artefacts/Debug|Release/*.app or *.exe
        local patterns = {
          -- macOS: standalone-only projects (juce_add_gui_app)
          root .. '/Builds/Ninja/Debug/**/*App_artefacts*/Debug/*.app/Contents/MacOS/*',
          root .. '/Builds/Ninja/Release/**/*App_artefacts*/Release/*.app/Contents/MacOS/*',
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/*.app/Contents/MacOS/*',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/*.app/Contents/MacOS/*',
          -- macOS: plugin projects with Standalone among FORMATS (nested like VST3/AU/CLAP)
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/Standalone/*.app/Contents/MacOS/*',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/Standalone/*.app/Contents/MacOS/*',
          -- Windows: standalone-only projects
          root .. '/Builds/Ninja/Debug/**/*App_artefacts*/Debug/*.exe',
          root .. '/Builds/Ninja/Release/**/*App_artefacts*/Release/*.exe',
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/*.exe',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/*.exe',
          -- Windows: plugin projects with Standalone among FORMATS
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/Standalone/*.exe',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/Standalone/*.exe',
        }

        local scheme = (M.loadDawConfig() or {}).scheme or 'Debug'
        local found = newestArtefact(filterPatternsByScheme(patterns, scheme))

        if not found then
          vim.notify('Failed to find standalone app in: ' .. root, vim.log.levels.ERROR)
          error('Standalone executable not found. Build project first.')
        end

        return found
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
      args = {},

    },
    {
      name = 'Attach to DAW (VST3)',
      type = plugin_adapter,
      -- Windows: launch DAW through debugger (owns process from birth, tracks all DLL loads)
      -- Mac: attach to already-running DAW
      request = is_windows and 'launch' or 'attach',
      console = 'integratedTerminal',
      pid = not is_windows and getDawPid or nil,
      program = function()
        if is_windows then
          -- Launch mode: program is the DAW executable
          local cfg = require('dap.configurations').loadDawConfig()
          if cfg and cfg.dawPath then return cfg.dawPath end
          error('DAW path not configured. Run F5 to configure.')
        end
        -- Mac: attach mode, program is the plugin binary
        local root = vim.fn.getcwd()
        local patterns = {
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/VST3/*.vst3/Contents/MacOS/*',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/VST3/*.vst3/Contents/MacOS/*',
        }
        local scheme = (M.loadDawConfig() or {}).scheme or 'Debug'
        local found = newestArtefact(filterPatternsByScheme(patterns, scheme))
        if found then return found end
        error('VST3 plugin not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
    },
    {
      name = 'Attach to DAW (AU)',
      type = plugin_adapter,
      request = 'attach',
      pid = getDawPid,
      program = function()
        local root = vim.fn.getcwd()
        local patterns = {
          -- macOS only (no AU on Windows)
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/AU/*.component/Contents/MacOS/*',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/AU/*.component/Contents/MacOS/*',
        }
        local scheme = (M.loadDawConfig() or {}).scheme or 'Debug'
        local found = newestArtefact(filterPatternsByScheme(patterns, scheme))
        if found then
          return found
        end
        error('AU plugin not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
    },
    {
      name = 'Attach to DAW (VST)',
      type = plugin_adapter,
      request = 'attach',
      pid = getDawPid,
      program = function()
        local root = vim.fn.getcwd()
        local patterns = {
          -- macOS
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/VST/*.vst/Contents/MacOS/*',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/VST/*.vst/Contents/MacOS/*',
          -- Windows
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/VST/*.dll',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/VST/*.dll',
        }
        local scheme = (M.loadDawConfig() or {}).scheme or 'Debug'
        local found = newestArtefact(filterPatternsByScheme(patterns, scheme))
        if found then
          return found
        end
        error('VST plugin not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
    },
    {
      name = 'Attach to DAW (AAX)',
      type = plugin_adapter,
      request = 'attach',
      pid = getDawPid,
      program = function()
        local root = vim.fn.getcwd()
        local patterns = {
          -- macOS
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/AAX/*.aaxplugin/Contents/MacOS/*',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/AAX/*.aaxplugin/Contents/MacOS/*',
          -- Windows
          root .. '/Builds/Ninja/Debug/**/*artefacts*/Debug/AAX/*.aaxplugin/Contents/x64/*.aaxplugin',
          root .. '/Builds/Ninja/Release/**/*artefacts*/Release/AAX/*.aaxplugin/Contents/x64/*.aaxplugin',
        }
        local scheme = (M.loadDawConfig() or {}).scheme or 'Debug'
        local found = newestArtefact(filterPatternsByScheme(patterns, scheme))
        if found then
          return found
        end
        error('AAX plugin not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
    },
    {
      name = 'Attach to DAW (CLAP)',
      type = plugin_adapter,
      request = 'attach',
      pid = getDawPid,
      program = function()
        local root = vim.fn.getcwd()
        -- jam_clap builds CLAP as a raw CMake MODULE target (PluginBuilder.cmake),
        -- not through JUCE's FORMATS artefact pipeline — it never lands under
        -- {TARGET}_artefacts/{Config}/CLAP/ like VST3/AU/AAX do. Output sits directly
        -- in the per-config build dir: Builds/Ninja/{Config}/{PRODUCT_NAME}.clap
        local patterns = {
          -- macOS
          root .. '/Builds/Ninja/Debug/**/*.clap/Contents/MacOS/*',
          root .. '/Builds/Ninja/Release/**/*.clap/Contents/MacOS/*',
          -- Windows
          root .. '/Builds/Ninja/Debug/**/*.clap',
          root .. '/Builds/Ninja/Release/**/*.clap',
        }
        local scheme = (M.loadDawConfig() or {}).scheme or 'Debug'
        local found = newestArtefact(filterPatternsByScheme(patterns, scheme))
        if found then
          return found
        end
        error('CLAP plugin not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
    },
    {
      name = 'Attach to Process',
      type = plugin_adapter,
      request = 'attach',
      pid = require('dap.utils').pick_process,
      cwd = '${workspaceFolder}',
    },
    {
      name = 'Launch Custom Executable',
      type = plugin_adapter,
      request = 'launch',
      program = function()
        return vim.fn.input('Executable: ', vim.fn.getcwd() .. '/', 'file')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
      args = function()
        local argsStr = vim.fn.input('Arguments: ')
        return vim.split(argsStr, ' ', { trimempty = true })
      end,
    },
  }

  -- Share configurations for C and Objective-C++
  dap.configurations.c = dap.configurations.cpp
  dap.configurations.objcpp = dap.configurations.cpp
end

-- Get DAP configuration name based on format from .nvim-dap-config
function M.getConfigNameForFormat(format)
  local mapping = {
    VST3 = 'Attach to DAW (VST3)',
    AU = 'Attach to DAW (AU)',
    VST = 'Attach to DAW (VST)',
    AAX = 'Attach to DAW (AAX)',
    CLAP = 'Attach to DAW (CLAP)',
  }
  return mapping[format]
end

return M
