-- DAP debug configurations for C++/JUCE
-- SSOT for debug configuration management
local M = {}

-- ============================================================================
-- CONFIG FILE MANAGEMENT (SSOT)
-- ============================================================================

local function getConfigFilePath()
  return vim.fn.getcwd() .. '/.nvim-dap-config'
end

-- Load .nvim-dap-config as Lua table
-- FAIL FAST = FAIL? FAST FIX!
-- Any problem → IMMEDIATELY show dialog and let user fix
-- Returns config if valid, shows dialog and returns result if invalid
function M.loadDawConfig(callback)
  local configFile = getConfigFilePath()
  
  -- File doesn't exist → show dialog immediately
  if vim.fn.filereadable(configFile) ~= 1 then
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- File exists but has invalid Lua syntax → delete and show dialog immediately
  local ok, config = pcall(dofile, configFile)
  if not ok then
    vim.notify('DAP config corrupted. Reconfiguring...', vim.log.levels.WARN)
    vim.fn.delete(configFile)
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- Config returned nil → delete and show dialog immediately
  if not config then
    vim.notify('DAP config empty. Reconfiguring...', vim.log.levels.WARN)
    vim.fn.delete(configFile)
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- Missing format field → show dialog immediately
  if not config.format or config.format == '' then
    vim.notify('DAP config missing format. Reconfiguring...', vim.log.levels.WARN)
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- Missing daw field → show dialog immediately
  if not config.daw or config.daw == '' then
    vim.notify('DAP config missing daw. Reconfiguring...', vim.log.levels.WARN)
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- Missing dawPath field → show dialog immediately
  if not config.dawPath or config.dawPath == '' then
    vim.notify('DAP config missing dawPath. Reconfiguring...', vim.log.levels.WARN)
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- Invalid dawPath → show dialog immediately
  if vim.fn.filereadable(config.dawPath) ~= 1 then
    vim.notify('DAP config dawPath invalid: ' .. config.dawPath .. '. Reconfiguring...', vim.log.levels.WARN)
    M.showDawFormatDialog(callback)
    return nil
  end
  
  -- Missing buildScheme field → show dialog immediately
  if not config.buildScheme or config.buildScheme == '' then
    vim.notify('DAP config missing buildScheme. Reconfiguring...', vim.log.levels.WARN)
    M.showDawFormatDialog(callback)
    return nil
  end
  
  return config
end

-- Save .nvim-dap-config as Lua table (self-documented)
-- Only fails if write fails (disk full, permissions) - beyond our control
function M.saveDawConfig(format, daw, dawPath, buildScheme)
  local configFile = getConfigFilePath()
  local content = string.format(
    '-- DAP Debug Configuration\n' ..
    '-- Generated by Neovim DAP\n' ..
    'return {\n' ..
    '  format = "%s",        -- Plugin format (VST3, AU, VST, AAX)\n' ..
    '  daw = "%s",           -- DAW name (for display/killall)\n' ..
    '  dawPath = "%s",       -- Absolute path to DAW executable\n' ..
    '  buildScheme = "%s",   -- Build scheme (Debug, Release)\n' ..
    '}',
    format,
    daw,
    dawPath,
    buildScheme
  )
  
  local ok, err = pcall(vim.fn.writefile, vim.split(content, '\n'), configFile)
  if not ok then
    vim.notify('Failed to write DAP config (disk/permissions issue): ' .. tostring(err), vim.log.levels.ERROR)
    return false
  end
  
  return true
end

-- Show dialog to configure format, DAW, and build scheme
-- User must provide all fields (validation happens in dialog)
function M.showDawFormatDialog(callback)
  local formats = { 'VST3', 'AU', 'VST', 'AAX' }
  
  vim.ui.select(formats, { prompt = 'Select plugin format:' }, function(format)
    if not format then
      vim.notify('DAP config cancelled', vim.log.levels.WARN)
      return
    end
    
    -- Select build scheme
    local schemes = { 'Debug', 'Release' }
    vim.ui.select(schemes, { prompt = 'Select build scheme:' }, function(buildScheme)
      if not buildScheme then
        vim.notify('DAP config cancelled', vim.log.levels.WARN)
        return
      end
      
      -- Browse for DAW .app bundle using picker with custom items
      local apps_dir = '/Applications'
      local handle = io.popen('find "' .. apps_dir .. '" -maxdepth 2 -name "*.app" -type d 2>/dev/null')
      if not handle then
        vim.notify('Failed to list applications', vim.log.levels.ERROR)
        return
      end
      
      local apps = {}
      for line in handle:lines() do
        table.insert(apps, { text = line, file = line })
      end
      handle:close()
      
      if #apps == 0 then
        vim.notify('No applications found in ' .. apps_dir, vim.log.levels.WARN)
        return
      end
      
      Snacks.picker({
        items = apps,
        prompt = 'Select DAW Application: ',
        format = 'file',
        confirm = function(picker, item)
          if not item or not item.file then
            vim.notify('DAP config cancelled: No DAW selected', vim.log.levels.WARN)
            picker:close()
            return
          end
          
          local dawPath = item.file
          
          -- If user selected .app bundle, find executable inside Contents/MacOS/
          if dawPath:match('%.app/?$') then
            local appName = vim.fn.fnamemodify(dawPath, ':t:r')  -- Get app name without .app
            dawPath = dawPath:gsub('/$', '') .. '/Contents/MacOS/' .. appName
          end
          
          -- Verify path exists - if not, show dialog again
          if vim.fn.filereadable(dawPath) ~= 1 then
            vim.notify('DAW executable not found: ' .. dawPath .. '. Try again.', vim.log.levels.ERROR)
            picker:close()
            vim.defer_fn(function() M.showDawFormatDialog(callback) end, 100)
            return
          end
          
          -- Extract DAW name from path
          local daw = vim.fn.fnamemodify(dawPath, ':t')
          
          -- Save config
          local ok = M.saveDawConfig(format, daw, dawPath, buildScheme)
          if not ok then
            picker:close()
            return
          end
          
          vim.notify(string.format('DAP config saved: %s + %s (%s)', format, daw, buildScheme), vim.log.levels.INFO)
          
          if callback then
            callback({ format = format, daw = daw, dawPath = dawPath, buildScheme = buildScheme })
          end
          
          picker:close()
        end,
      })
    end)
  end)
end

-- ============================================================================
-- DAP CONFIGURATIONS
-- ============================================================================

-- Helper to get DAW PID from config
local function getDawPid()
  local config = M.loadDawConfig()
  if not config then
    return nil
  end
  
  local handle = io.popen("pgrep -x '" .. config.daw .. "' 2>/dev/null | head -1")
  if not handle then
    error('Failed to search for DAW process: ' .. config.daw)
  end
  
  local pid = handle:read('*l')
  handle:close()
  
  if pid and tonumber(pid) then
    return tonumber(pid)
  end
  
  error('DAW not running: ' .. config.daw .. '. Launch it first.')
end

function M.setup()
  local dap = require('dap')

  dap.configurations.cpp = {
    {
      name = 'Launch Standalone',
      type = 'codelldb',
      request = 'launch',
      program = function()
        local root = vim.fn.getcwd()
        local patterns = {
          -- macOS
          root .. '/Builds/Ninja/*artefacts*/Debug/Standalone/*.app/Contents/MacOS/*',
          root .. '/Builds/Ninja/*artefacts*/Release/Standalone/*.app/Contents/MacOS/*',
          -- Windows
          root .. '/Builds/Ninja/*artefacts*/Debug/Standalone/*.exe',
          root .. '/Builds/Ninja/*artefacts*/Release/Standalone/*.exe',
        }
        for _, pattern in ipairs(patterns) do
          local matches = vim.fn.glob(pattern, false, true)
          if #matches > 0 then
            return matches[1]
          end
        end
        error('Standalone executable not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
      args = {},
    },
    {
      name = 'Attach to DAW (VST3)',
      type = 'codelldb',
      request = 'attach',
      pid = getDawPid,
      program = function()
        local root = vim.fn.getcwd()
        local patterns = {
          -- macOS
          root .. '/Builds/Ninja/*artefacts*/Debug/VST3/*.vst3/Contents/MacOS/*',
          root .. '/Builds/Ninja/*artefacts*/Release/VST3/*.vst3/Contents/MacOS/*',
          -- Windows
          root .. '/Builds/Ninja/*artefacts*/Debug/VST3/*.vst3/Contents/x86_64-win/*.vst3',
          root .. '/Builds/Ninja/*artefacts*/Release/VST3/*.vst3/Contents/x86_64-win/*.vst3',
        }
        for _, pattern in ipairs(patterns) do
          local matches = vim.fn.glob(pattern, false, true)
          if #matches > 0 then
            return matches[1]
          end
        end
        error('VST3 plugin not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
    },
    {
      name = 'Attach to DAW (AU)',
      type = 'codelldb',
      request = 'attach',
      pid = getDawPid,
      program = function()
        local root = vim.fn.getcwd()
        local patterns = {
          -- macOS only (no AU on Windows)
          root .. '/Builds/Ninja/*artefacts*/Debug/AU/*.component/Contents/MacOS/*',
          root .. '/Builds/Ninja/*artefacts*/Release/AU/*.component/Contents/MacOS/*',
        }
        for _, pattern in ipairs(patterns) do
          local matches = vim.fn.glob(pattern, false, true)
          if #matches > 0 then
            return matches[1]
          end
        end
        error('AU plugin not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
    },
    {
      name = 'Attach to DAW (VST)',
      type = 'codelldb',
      request = 'attach',
      pid = getDawPid,
      program = function()
        local root = vim.fn.getcwd()
        local patterns = {
          -- macOS
          root .. '/Builds/Ninja/*artefacts*/Debug/VST/*.vst/Contents/MacOS/*',
          root .. '/Builds/Ninja/*artefacts*/Release/VST/*.vst/Contents/MacOS/*',
          -- Windows
          root .. '/Builds/Ninja/*artefacts*/Debug/VST/*.dll',
          root .. '/Builds/Ninja/*artefacts*/Release/VST/*.dll',
        }
        for _, pattern in ipairs(patterns) do
          local matches = vim.fn.glob(pattern, false, true)
          if #matches > 0 then
            return matches[1]
          end
        end
        error('VST plugin not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
    },
    {
      name = 'Attach to DAW (AAX)',
      type = 'codelldb',
      request = 'attach',
      pid = getDawPid,
      program = function()
        local root = vim.fn.getcwd()
        local patterns = {
          -- macOS
          root .. '/Builds/Ninja/*artefacts*/Debug/AAX/*.aaxplugin/Contents/MacOS/*',
          root .. '/Builds/Ninja/*artefacts*/Release/AAX/*.aaxplugin/Contents/MacOS/*',
          -- Windows
          root .. '/Builds/Ninja/*artefacts*/Debug/AAX/*.aaxplugin/Contents/x64/*.aaxplugin',
          root .. '/Builds/Ninja/*artefacts*/Release/AAX/*.aaxplugin/Contents/x64/*.aaxplugin',
        }
        for _, pattern in ipairs(patterns) do
          local matches = vim.fn.glob(pattern, false, true)
          if #matches > 0 then
            return matches[1]
          end
        end
        error('AAX plugin not found. Build project first.')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
    },
    {
      name = 'Attach to Process',
      type = 'codelldb',
      request = 'attach',
      pid = require('dap.utils').pick_process,
      cwd = '${workspaceFolder}',
    },
    {
      name = 'Launch Custom Executable',
      type = 'codelldb',
      request = 'launch',
      program = function()
        return vim.fn.input('Executable: ', vim.fn.getcwd() .. '/', 'file')
      end,
      cwd = '${workspaceFolder}',
      stopOnEntry = false,
      args = function()
        local argsStr = vim.fn.input('Arguments: ')
        return vim.split(argsStr, ' ', { trimempty = true })
      end,
    },
  }

  -- Share configurations for C and Objective-C++
  dap.configurations.c = dap.configurations.cpp
  dap.configurations.objcpp = dap.configurations.cpp
end

-- Get DAP configuration name based on format from .nvim-dap-config
function M.getConfigNameForFormat(format)
  local mapping = {
    VST3 = 'Attach to DAW (VST3)',
    AU = 'Attach to DAW (AU)',
    VST = 'Attach to DAW (VST)',
    AAX = 'Attach to DAW (AAX)',
  }
  return mapping[format]
end

return M
