-- core/keymaps-generator.lua
-- Generates lua/core/keymaps.lua from the lexicon at doc/KEYMAPS.md.
-- verify() is the launch gate: sha256 of the lexicon is embedded in the
-- generated banner; on mismatch the file is re-generated. Validation
-- failure never destroys the last-good generated file.
local M = {}

local MD_PATH  = vim.fn.stdpath('config') .. '/doc/KEYMAPS.md'
local OUT_PATH = vim.fn.stdpath('config') .. '/lua/core/keymaps.lua'

-- Fixed vocabularies — a token outside these is a validation error.
local INVOCATIONS = { init = true, event = true, plugin = true }
local OPTS_TOKENS = { sync = true, expr = true, silent = true }
local GLOBAL_ROOTS = { vim = true, Snacks = true }
local SUPPORTS_METHODS = { inlayHint = 'textDocument_inlayHint' }
local ACTION_MODULES = { actions = 'core/actions.lua', build = 'core/build.lua' }

-- Column positions in the two contract table schemas (## groups / ## keys:).
local GROUP_COLUMNS = { name = 1, func = 2, invocation = 3, prefix = 4, requires = 5, parent = 6, guard = 7 }
local KEY_COLUMNS = { key = 1, mode = 2, action = 3, opts = 4, desc = 5 }

local BANNER = [[
-- ░████          ░████████░████       ░████░████    ░██████████        ░██████████        ░████████
-- ░████        ░██████████░██████   ░██████░████  ░██████████████    ░██████████████    ░████████████
-- ░████      ░██████        ░████████████  ░████░██████     ░██████░██████     ░██████░██████   ░██████
-- ░████      ░████            ░████████    ░████░████         ░██  ░████         ░████░████       ░████
-- ░████      ░██████████        ░████      ░████░████              ░████         ░████░████       ░████
-- ░████      ░██████████        ░████      ░████░████              ░████         ░████░████       ░████
-- ░████      ░████            ░████████    ░████░████         ░██  ░████         ░████░████       ░████
-- ░██████    ░██████        ░████████████  ░████░██████     ░██████░██████     ░██████░████       ░████
--   ░████████  ░██████████░██████   ░██████░████  ░██████████████    ░██████████████  ░████       ░████
--     ░██████    ░████████░████       ░████░████    ░██████████        ░██████████    ░████       ░████
--
--                                       FOR YOUR EYES ONLY
--
-- GENERATED CODE — READ ONLY
--
-- Generated by nvim/lua/core/keymaps-generator.lua
-- Source lexicon files:
--   nvim/doc/KEYMAPS.md
--
-- Edit the lexicon file, never this file.
]]

-- | a | b | c | → { 'a', 'b', 'c' } (inner pipes never occur in the lexicon)
local function splitRow(line)
  local cells = {}
  for cell in line:gmatch('|([^|]*)') do
    cells[#cells + 1] = vim.trim(cell)
  end
  return cells
end

local function isRuleRow(cells)
  for _, c in ipairs(cells) do
    if c ~= '' and not c:match('^:?%-+:?$') then return false end
  end
  return true
end

-- Parses contract sections. Returns groups (ordered) + per-group key rows, or
-- nil + error message.
local function parse(text)
  local groups, groupsByName, currentKeys = {}, {}, nil
  local lineNumber = 0

  for line in (text .. '\n'):gmatch('(.-)\n') do
    lineNumber = lineNumber + 1
    local keysName = line:match('^## keys:%s*(%S+)')

    if line:match('^## groups%s*$') then
      currentKeys = 'groups'
    elseif keysName then
      if not groupsByName[keysName] then
        return nil, ('KEYMAPS.md:%d: unknown group %q'):format(lineNumber, keysName)
      end
      currentKeys = keysName
    elseif line:match('^#') then
      currentKeys = nil
    elseif currentKeys and line:match('^|') then
      local cells = splitRow(line)
      if not isRuleRow(cells) and cells[1] ~= 'group' and cells[1] ~= 'key' then
        if currentKeys == 'groups' then
          local group = {
            name = cells[GROUP_COLUMNS.name], func = cells[GROUP_COLUMNS.func],
            invocation = cells[GROUP_COLUMNS.invocation], prefix = cells[GROUP_COLUMNS.prefix],
            requires = cells[GROUP_COLUMNS.requires], parent = cells[GROUP_COLUMNS.parent],
            guard = cells[GROUP_COLUMNS.guard], keys = {},
          }
          if group.parent == '' and not INVOCATIONS[group.invocation] then
            return nil, ('KEYMAPS.md:%d: invalid invocation %q'):format(lineNumber, group.invocation)
          end
          if group.parent ~= '' and not groupsByName[group.parent] then
            return nil, ('KEYMAPS.md:%d: unknown parent %q'):format(lineNumber, group.parent)
          end
          if group.parent ~= '' then
            local supportsMethod = group.guard:match('^supports=(%S+)$')
            local isClientGuard = group.guard:match('^client=%S+$') ~= nil
            local isSupportsGuard = supportsMethod ~= nil and SUPPORTS_METHODS[supportsMethod] ~= nil
            if not (isClientGuard or isSupportsGuard) then
              return nil, ('KEYMAPS.md:%d: invalid guard %q'):format(lineNumber, group.guard)
            end
          end
          groups[#groups + 1] = group
          groupsByName[group.name] = group
        else
          local keyCell = cells[KEY_COLUMNS.key]
          local row = { key = keyCell:match('^`(.*)`$') or keyCell, mode = cells[KEY_COLUMNS.mode],
                        action = cells[KEY_COLUMNS.action], opts = cells[KEY_COLUMNS.opts],
                        desc = cells[KEY_COLUMNS.desc], line = lineNumber }
          for token in row.opts:gmatch('[^,%s]+') do
            if not OPTS_TOKENS[token] then
              return nil, ('KEYMAPS.md:%d: invalid opts token %q'):format(lineNumber, token)
            end
          end
          local seen = groupsByName[currentKeys].keys
          for _, existing in ipairs(seen) do
            if existing.key == row.key and existing.mode == row.mode then
              return nil, ('KEYMAPS.md:%d: duplicate %s-mode key %q in group %q'):format(lineNumber, row.mode, row.key, currentKeys)
            end
          end
          seen[#seen + 1] = row
        end
      end
    end
  end

  return { list = groups, byName = groupsByName }
end

local function parseRequires(group)
  local aliases = {}
  local list = {}
  if group.requires ~= '' then
    for spec in group.requires:gmatch('[^,]+') do
      spec = vim.trim(spec)
      local moduleName, alias = spec:match('^(%S+)%s+as%s+(%S+)$')
      if not moduleName then
        moduleName = spec
        alias = spec:match('([%w_]+)$')
      end
      aliases[alias] = true
      list[#list + 1] = { module = moduleName, alias = alias }
    end
  end
  return aliases, list
end

-- Bare dotted rows (no backtick, no @, no call parens) emit a direct
-- reference — the root must be a required alias or a known global, or the
-- generated code would evaluate to nil at bind time.
local function validateBareRoots(groups)
  for _, group in ipairs(groups.list) do
    local owner = group.parent ~= '' and groups.byName[group.parent] or group
    local aliases = parseRequires(owner)
    for _, row in ipairs(group.keys) do
      local isBare = not row.action:match('^`') and not row.action:match('^@') and not row.action:find('%(')
      if isBare then
        local root = row.action:match('^([^.]+)')
        if not (GLOBAL_ROOTS[root] or aliases[root]) then
          return ('KEYMAPS.md:%d: bare reference root %q is neither required nor a known global'):format(row.line, root)
        end
      end
    end
  end
  return nil
end

-- @actions.name / @build.name must exist as 'function M.name' or 'M.name ='
-- in the owning module file.
local function validateActionRefs(groups)
  local sources = {}
  for _, group in ipairs(groups.list) do
    for _, row in ipairs(group.keys) do
      local moduleKey, funcName = row.action:match('^@(%w+)%.([%w_]+)$')
      if moduleKey then
        if not ACTION_MODULES[moduleKey] then
          return ('KEYMAPS.md:%d: unknown action module @%s'):format(row.line, moduleKey)
        end
        if not sources[moduleKey] then
          local file = io.open(vim.fn.stdpath('config') .. '/lua/' .. ACTION_MODULES[moduleKey], 'r')
          if not file then return ('missing action module: ' .. ACTION_MODULES[moduleKey]) end
          sources[moduleKey] = file:read('*a')
          file:close()
        end
        if not (sources[moduleKey]:find('function M%.' .. funcName .. '%f[^%w_]')
                or sources[moduleKey]:find('M%.' .. funcName .. '%s*=')) then
          return ('KEYMAPS.md:%d: @%s.%s not found in %s'):format(row.line, moduleKey, funcName, ACTION_MODULES[moduleKey])
        end
      end
    end
  end
  return nil
end

local function quote(s)
  return "'" .. s:gsub('\\', '\\\\'):gsub("'", "\\'") .. "'"
end

-- Renders the action cell into (rhsExpression, requiredLocals).
local function renderAction(row, group)
  local needs = {}
  local action = row.action
  local sync = row.opts:find('sync') ~= nil
  local literal = action:match('^`(.*)`$')

  if literal then return quote(literal), needs end

  local rhs
  local moduleKey, funcName = action:match('^@(%w+)%.([%w_]+)$')
  if moduleKey then
    needs[moduleKey] = true
    rhs = moduleKey .. '.' .. funcName
  elseif action:find('%(') then
    local path = action:match('^([^(]+)')
    local args = action:sub(#path + 1)
    local root = path:match('^([^.]+)')
    if GLOBAL_ROOTS[root] or (group.aliases and group.aliases[root]) then
      rhs = 'function() ' .. path .. args .. ' end'
    else
      local moduleName, callName = path:match('^(.*)%.([%w_]+)$')
      rhs = 'function() require(' .. quote(moduleName) .. ').' .. callName .. args .. ' end'
    end
  else
    rhs = action
  end

  if sync then
    needs.actions = true
    local body = rhs:match('^function%(%)%s(.*)%send$') or (rhs .. '()')
    rhs = 'function() actions.splitSyncOnce(); ' .. body .. ' end'
  end

  return rhs, needs
end

local function renderOpts(row, group)
  local parts = {}
  if group.invocation == 'event' then parts[#parts + 1] = 'buffer = event.buf' end
  if row.desc ~= '' then
    local desc = (group.prefix ~= '' and (group.prefix .. ' ') or '') .. row.desc
    parts[#parts + 1] = 'desc = ' .. quote(desc)
  end
  if row.opts:find('expr') then parts[#parts + 1] = 'expr = true' end
  if row.opts:find('silent') then parts[#parts + 1] = 'silent = true' end
  return '{ ' .. table.concat(parts, ', ') .. ' }'
end

local function renderMode(mode)
  local modes = {}
  for m in mode:gmatch('[^,%s]+') do modes[#modes + 1] = quote(m) end
  if #modes == 1 then return modes[1] end
  return '{ ' .. table.concat(modes, ', ') .. ' }'
end

local function renderRows(group, parentGroup, out, indent)
  for _, row in ipairs(group.keys) do
    local rhs, needs = renderAction(row, parentGroup)
    for key in pairs(needs) do parentGroup.needs[key] = true end
    out[#out + 1] = ('%svim.keymap.set(%s, %s, %s, %s)'):format(
      indent, renderMode(row.mode), quote(row.key), rhs, renderOpts(row, parentGroup))
  end
end

local function renderGuard(guard)
  local clientName = guard:match('^client=(%S+)$')
  if clientName then return ('client and client.name == %s'):format(quote(clientName)) end
  local method = guard:match('^supports=(%S+)$')
  return ('client and client:supports_method(vim.lsp.protocol.Methods.%s)'):format(SUPPORTS_METHODS[method])
end

local function emitGroup(group, groups, out)
  local body = {}
  group.needs = {}
  local requireLines = {}

  local aliases, requireList = parseRequires(group)
  group.aliases = aliases
  for _, entry in ipairs(requireList) do
    requireLines[#requireLines + 1] = ('  local %s = require(%s)'):format(entry.alias, quote(entry.module))
  end

  renderRows(group, group, body, '  ')

  local subgroups = {}
  for _, candidate in ipairs(groups.list) do
    if candidate.parent == group.name then subgroups[#subgroups + 1] = candidate end
  end
  if #subgroups > 0 then
    body[#body + 1] = ''
    body[#body + 1] = '  local client = vim.lsp.get_client_by_id(event.data.client_id)'
    for _, subgroup in ipairs(subgroups) do
      body[#body + 1] = ('  if %s then'):format(renderGuard(subgroup.guard))
      renderRows(subgroup, group, body, '    ')
      body[#body + 1] = '  end'
    end
  end

  for moduleKey in pairs(group.needs) do
    requireLines[#requireLines + 1] = ('  local %s = require(%s)'):format(moduleKey, quote('core.' .. moduleKey))
  end
  table.sort(requireLines)

  out[#out + 1] = ('function M.%s(%s)'):format(group.func, group.invocation == 'event' and 'event' or '')
  for _, line in ipairs(requireLines) do out[#out + 1] = line end
  if #requireLines > 0 then out[#out + 1] = '' end
  for _, line in ipairs(body) do out[#out + 1] = line end
  out[#out + 1] = 'end'
  out[#out + 1] = ''
end

local function emit(groups, hash)
  local out = {}
  out[#out + 1] = BANNER .. '-- LEXICON: sha256:' .. hash
  out[#out + 1] = 'local M = {}'
  out[#out + 1] = ''
  for _, group in ipairs(groups.list) do
    if group.parent == '' then emitGroup(group, groups, out) end
  end
  out[#out + 1] = 'return M'
  return table.concat(out, '\n') .. '\n'
end

function M.verify()
  local mdFile = io.open(MD_PATH, 'r')
  if not mdFile then
    vim.notify('[keymaps-generator] lexicon missing: ' .. MD_PATH, vim.log.levels.ERROR)
    return
  end
  local text = mdFile:read('*a')
  mdFile:close()
  local hash = vim.fn.sha256(text)

  local existing = io.open(OUT_PATH, 'r')
  if existing then
    local head = existing:read(4096)
    existing:close()
    if head and head:find('LEXICON: sha256:' .. hash, 1, true) then return end
  end

  local groups, parseError = parse(text)
  if not groups then
    vim.notify('[keymaps-generator] ' .. parseError .. ' — keeping last-good keymaps.lua', vim.log.levels.ERROR)
    return
  end
  local validationError = validateBareRoots(groups) or validateActionRefs(groups)
  if validationError then
    vim.notify('[keymaps-generator] ' .. validationError .. ' — keeping last-good keymaps.lua', vim.log.levels.ERROR)
    return
  end

  local outFile = assert(io.open(OUT_PATH, 'w'))
  outFile:write(emit(groups, hash))
  outFile:close()
  vim.notify('[keymaps-generator] keymaps.lua regenerated from KEYMAPS.md', vim.log.levels.INFO)
end

return M
