-- ░████          ░████████░████       ░████░████    ░██████████        ░██████████        ░████████
-- ░████        ░██████████░██████   ░██████░████  ░██████████████    ░██████████████    ░████████████
-- ░████      ░██████        ░████████████  ░████░██████     ░██████░██████     ░██████░██████   ░██████
-- ░████      ░████            ░████████    ░████░████         ░██  ░████         ░████░████       ░████
-- ░████      ░██████████        ░████      ░████░████              ░████         ░████░████       ░████
-- ░████      ░██████████        ░████      ░████░████              ░████         ░████░████       ░████
-- ░████      ░████            ░████████    ░████░████         ░██  ░████         ░████░████       ░████
-- ░██████    ░██████        ░████████████  ░████░██████     ░██████░██████     ░██████░████       ░████
--   ░████████  ░██████████░██████   ░██████░████  ░██████████████    ░██████████████  ░████       ░████
--     ░██████    ░████████░████       ░████░████    ░██████████        ░██████████    ░████       ░████
--
--                                       FOR YOUR EYES ONLY
--
-- GENERATED CODE — READ ONLY
--
-- Generated by nvim/lua/core/keymaps-generator.lua
-- Source lexicon files:
--   nvim/doc/KEYMAPS.md
--
-- Edit the lexicon file, never this file.
-- LEXICON: sha256:c89e2ee8a6bbce532b45ec7cbf7a2f4d09f9a2c70a9ff68c3a6f77a1e98f10f1
local M = {}

function M.setup()
  local actions = require('core.actions')

  vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>', { desc = 'Clear search highlights' })
  vim.keymap.set('n', '<leader>q', actions.toggleDiagnosticList, { desc = 'Toggle diagnostic list' })
  vim.keymap.set('n', '<C-s>', actions.saveAllAndQuit, { desc = 'Save all and quit' })
  vim.keymap.set('n', '<C-c>', actions.smart_quit, { desc = 'Quit with save/discard prompt' })
  vim.keymap.set('n', '<leader>tt', function() require('core.tui').tit() end, { desc = 'Open TIT (git TUI)' })
  vim.keymap.set('n', '<leader>tc', function() require('core.tui').cake() end, { desc = 'Open Cake TUI' })
  vim.keymap.set('n', '<leader>bd', function() require('core.doxygen').build() end, { desc = 'Build doxygen docs' })
  vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
  vim.keymap.set('n', '<leader>tx', actions.closeAllTerminals, { desc = 'Close all terminal windows' })
  vim.keymap.set('n', '<leader>rw', ':%s/\\<<C-r><C-w>\\>/<C-r><C-w>/gI<Left><Left><Left>', { desc = 'Replace word (exact)' })
  vim.keymap.set('v', '<leader>rw', '"hy:%s/\\<<C-r>h\\>/<C-r>h/gI<Left><Left><Left>', { desc = 'Replace selection (exact)' })
  vim.keymap.set('n', '<leader>rc', ':%s/<C-r><C-w>/<C-r><C-w>/gI<Left><Left><Left>', { desc = 'Replace word (contains)' })
  vim.keymap.set('v', '<leader>rc', '"hy:%s/<C-r>h/<C-r>h/gI<Left><Left><Left>', { desc = 'Replace selection (contains)' })
  vim.keymap.set('n', '<leader>ss', function() require('lsp.header-source').syncSplit() end, { desc = 'Sync header/source split' })
  vim.keymap.set('n', '<leader>s\\', '<C-w>v', { desc = 'Split vertical' })
  vim.keymap.set('n', '<leader>s-', '<C-w>s', { desc = 'Split horizontal' })
  vim.keymap.set('n', '<leader>s=', '<C-w>=', { desc = 'Equal split sizes' })
  vim.keymap.set('n', '<leader><Tab>', '<C-w>o', { desc = 'Close other splits' })
  vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Focus left window' })
  vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Focus right window' })
  vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Focus lower window' })
  vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Focus upper window' })
  vim.keymap.set('n', '<leader>x', '<C-w>q', { desc = 'Close window' })
  vim.keymap.set('n', '<leader>[', actions.jumpBackSynced, { desc = 'Jump back (sync split)' })
  vim.keymap.set('n', '<leader>]', actions.jumpForwardSynced, { desc = 'Jump forward (sync split)' })
  vim.keymap.set('n', '<leader>p', ':pu<CR>', { desc = 'Paste below on new line' })
  vim.keymap.set('n', '<leader>P', ':pu!<CR>', { desc = 'Paste above on new line' })
  vim.keymap.set('i', '<Esc>', actions.formatOnEsc, { desc = 'Format on exit insert mode', expr = true })
  vim.keymap.set('v', '<Esc>', actions.formatOnEsc, { desc = 'Format on exit visual mode', expr = true })
  vim.keymap.set('n', '<Esc><Esc>', actions.formatBufferByFiletype, { desc = 'Format buffer' })
  vim.keymap.set('n', '<leader>ff', function() require('core.cmake-picker').files() end, { desc = 'Find files (cmake)' })
  vim.keymap.set('n', '<leader>fx', function() require('core.cmake-picker').open_explorer() end, { desc = 'Project explorer (cmake)' })
  vim.keymap.set('n', '<leader>fg', function() require('core.cmake-picker').grep() end, { desc = 'Find by grep (cmake)' })
  vim.keymap.set('n', '<leader>fr', function() require('core.cmake-picker').replace_grep() end, { desc = 'Project grep+replace (cmake)' })
  vim.keymap.set('n', '<leader>rg', function() require('core.cmake-picker').replace() end, { desc = 'Project replace (cmake)' })
  vim.keymap.set('v', '<leader>rg', '"zy<Cmd>lua require("core.cmake-picker").replace(vim.fn.getreg("z"))<CR>', { desc = 'Project replace selection (cmake)' })
  vim.keymap.set('n', '<leader>fb', function() actions.splitSyncOnce(); Snacks.picker.buffers() end, { desc = 'Find buffers' })
  vim.keymap.set('n', '<leader>fh', function() actions.splitSyncOnce(); Snacks.picker.help() end, { desc = 'Find help' })
  vim.keymap.set('n', '<leader>\\', function() Snacks.explorer.reveal() end, { desc = 'File explorer' })
  vim.keymap.set('n', '<leader>fk', function() Snacks.picker.keymaps() end, { desc = 'Find keymaps' })
  vim.keymap.set('n', '<leader>fw', function() actions.splitSyncOnce(); Snacks.picker.grep_word() end, { desc = 'Find current word' })
  vim.keymap.set('n', '<leader>fd', function() actions.splitSyncOnce(); Snacks.picker.diagnostics() end, { desc = 'Find diagnostics' })
  vim.keymap.set('n', '<leader>fR', function() actions.splitSyncOnce(); Snacks.picker.resume() end, { desc = 'Find resume' })
  vim.keymap.set('n', '<leader>f.', function() actions.splitSyncOnce(); Snacks.picker.recent() end, { desc = 'Find recent files' })
  vim.keymap.set('n', '<leader>/', function() Snacks.picker.lines() end, { desc = 'Search in buffer' })
  vim.keymap.set('n', '<leader>f/', function() actions.splitSyncOnce(); Snacks.picker.grep_buffers() end, { desc = 'Find in open files' })
  vim.keymap.set('n', '<leader>fn', function() actions.splitSyncOnce(); Snacks.picker.files({ cwd = vim.fn.stdpath('config') }) end, { desc = 'Find neovim files' })
end

function M.setupLsp(event)
  local actions = require('core.actions')

  vim.keymap.set('n', 'gd', function() require('lsp.header-source').smartDefinitionJump() end, { buffer = event.buf, desc = 'LSP: Go to definition' })
  vim.keymap.set('n', 'gr', function() actions.splitSyncOnce(); Snacks.picker.lsp_references() end, { buffer = event.buf, desc = 'LSP: Go to references' })
  vim.keymap.set('n', 'gI', function() actions.splitSyncOnce(); Snacks.picker.lsp_implementations() end, { buffer = event.buf, desc = 'LSP: Go to implementation' })
  vim.keymap.set('n', 'gD', function() actions.splitSyncOnce(); vim.lsp.buf.declaration() end, { buffer = event.buf, desc = 'LSP: Go to declaration' })
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, { buffer = event.buf, desc = 'LSP: Hover documentation' })
  vim.keymap.set('n', '<leader>ds', function() actions.splitSyncOnce(); Snacks.picker.lsp_symbols() end, { buffer = event.buf, desc = 'LSP: Document symbols' })
  vim.keymap.set('n', '<leader>ws', function() actions.splitSyncOnce(); Snacks.picker.lsp_workspace_symbols() end, { buffer = event.buf, desc = 'LSP: Workspace symbols' })
  vim.keymap.set('n', '<leader>rn', vim.lsp.buf.rename, { buffer = event.buf, desc = 'LSP: Rename symbol' })
  vim.keymap.set({ 'n', 'x' }, '<leader>ca', vim.lsp.buf.code_action, { buffer = event.buf, desc = 'LSP: Code action' })

  local client = vim.lsp.get_client_by_id(event.data.client_id)
  if client and client.name == 'clangd' then
    vim.keymap.set('n', 'gh', '<cmd>ClangdSwitchSourceHeader<CR>', { buffer = event.buf, desc = 'LSP: Switch header/source' })
    vim.keymap.set('n', '<leader>cc', function() require('lsp.cpp-stub').generateStub() end, { buffer = event.buf, desc = 'LSP: Generate C++ definition stub' })
    vim.keymap.set('n', '<leader>cv', function() require('lsp.cpp-stub').generateAllStubs() end, { buffer = event.buf, desc = 'LSP: Generate all missing C++ stubs' })
    vim.keymap.set('n', '<leader>c/', function() require('lsp.cpp-stub').toggleCommentPair() end, { buffer = event.buf, desc = 'LSP: Toggle comment in header + cpp' })
  end
  if client and client:supports_method(vim.lsp.protocol.Methods.textDocument_inlayHint) then
    vim.keymap.set('n', '<leader>th', function() vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = 0 })) end, { buffer = event.buf, desc = 'LSP: Toggle inlay hints' })
  end
end

function M.setupDap()
  local actions = require('core.actions')
  local build = require('core.build')
  local dap = require('dap')
  local dapui = require('dapui')

  vim.keymap.set('n', '<F5>', build.configureProject, { desc = 'DAP: Configure project' })
  vim.keymap.set('n', '<F10>', dap.step_over, { desc = 'DAP: Step over' })
  vim.keymap.set('n', '<F11>', dap.step_into, { desc = 'DAP: Step into' })
  vim.keymap.set('n', '<F12>', dap.step_out, { desc = 'DAP: Step out' })
  vim.keymap.set('n', '<leader>db', function() actions.splitSyncOnce(); dap.toggle_breakpoint() end, { desc = 'DAP: Toggle breakpoint' })
  vim.keymap.set('n', '<leader>dB', function() actions.splitSyncOnce(); dap.set_breakpoint(vim.fn.input('Condition: ')) end, { desc = 'DAP: Conditional breakpoint' })
  vim.keymap.set('n', '<leader>dl', function() actions.splitSyncOnce(); dap.set_breakpoint(nil, nil, vim.fn.input('Log message: ')) end, { desc = 'DAP: Log point' })
  vim.keymap.set('n', '<leader>dc', dap.continue, { desc = 'DAP: Continue' })
  vim.keymap.set('n', '<leader>di', dap.step_into, { desc = 'DAP: Step into' })
  vim.keymap.set('n', '<leader>do', dap.step_over, { desc = 'DAP: Step over' })
  vim.keymap.set('n', '<leader>dx', dap.step_out, { desc = 'DAP: Step out' })
  vim.keymap.set('n', '<leader>dp', dap.pause, { desc = 'DAP: Pause' })
  vim.keymap.set('n', '<leader>dr', function() dap.repl.open() end, { desc = 'DAP: Open REPL' })
  vim.keymap.set('n', '<leader>dL', dap.run_last, { desc = 'DAP: Run last' })
  vim.keymap.set('n', '<leader>du', dapui.toggle, { desc = 'DAP: Toggle UI' })
  vim.keymap.set('n', '<leader>de', dapui.eval, { desc = 'DAP: Evaluate expression' })
  vim.keymap.set('v', '<leader>de', dapui.eval, { desc = 'DAP: Evaluate selection' })
  vim.keymap.set('n', '<leader>dt', build.terminateAndNotify, { desc = 'DAP: Terminate + close DAW/App' })
  vim.keymap.set('n', '<leader>br', build.buildReleaseAndRun, { desc = 'DAP: Build release + run' })
  vim.keymap.set('n', '<leader>bb', build.buildDebugAndRun, { desc = 'DAP: Build debug + run' })
  vim.keymap.set('n', '<leader>bR', build.buildReleaseOnly, { desc = 'DAP: Build release only (no run)' })
  vim.keymap.set('n', '<leader>bB', build.buildDebugOnly, { desc = 'DAP: Build debug only (no run)' })
  vim.keymap.set('n', '<leader>bc', build.cleanBuild, { desc = 'DAP: Clean build' })
  vim.keymap.set('n', '<leader>bk', build.cleanOnly, { desc = 'DAP: Clean' })
end

function M.setupMiniPairs()
  local actions = require('core.actions')

  vim.keymap.set('i', ';', actions.jumpOutSemicolon, { desc = 'Jump out of )/} and add ;', expr = true })
end

function M.setupFlash()
  vim.keymap.set({ 'n', 'x', 'o' }, 's', function() require('flash').jump() end, { desc = 'Flash' })
  vim.keymap.set({ 'n', 'x', 'o' }, 'S', function() require('flash').treesitter() end, { desc = 'Flash Treesitter' })
  vim.keymap.set('o', 'r', function() require('flash').remote() end, { desc = 'Remote Flash' })
  vim.keymap.set({ 'o', 'x' }, 'R', function() require('flash').treesitter_search() end, { desc = 'Treesitter Search' })
  vim.keymap.set('c', '<c-s>', function() require('flash').toggle() end, { desc = 'Toggle Flash Search' })
end

function M.setupTextobjects()
  local select = require('nvim-treesitter-textobjects.select')

  vim.keymap.set({ 'x', 'o' }, 'aF', function() select.select_textobject('@function.outer', 'textobjects') end, { desc = 'around function' })
  vim.keymap.set({ 'x', 'o' }, 'iF', function() select.select_textobject('@function.inner', 'textobjects') end, { desc = 'inside function' })
  vim.keymap.set({ 'x', 'o' }, 'aC', function() select.select_textobject('@class.outer', 'textobjects') end, { desc = 'around class' })
  vim.keymap.set({ 'x', 'o' }, 'iC', function() select.select_textobject('@class.inner', 'textobjects') end, { desc = 'inside class' })
  vim.keymap.set({ 'x', 'o' }, 'aL', function() select.select_textobject('@loop.outer', 'textobjects') end, { desc = 'around loop' })
  vim.keymap.set({ 'x', 'o' }, 'iL', function() select.select_textobject('@loop.inner', 'textobjects') end, { desc = 'inside loop' })
  vim.keymap.set({ 'x', 'o' }, 'aI', function() select.select_textobject('@conditional.outer', 'textobjects') end, { desc = 'around if/conditional' })
  vim.keymap.set({ 'x', 'o' }, 'iI', function() select.select_textobject('@conditional.inner', 'textobjects') end, { desc = 'inside if/conditional' })
end

function M.setupSnippets()
  local actions = require('core.actions')
  local snacks = require('snacks')

  vim.keymap.set('i', '<C-l>', function() require('luasnip').jump(1) end, { desc = 'Snippet jump forward', silent = true })
  vim.keymap.set('i', '<C-h>', function() require('luasnip').jump(-1) end, { desc = 'Snippet jump back', silent = true })
  vim.keymap.set('i', '<C-e>', actions.cycleSnippetChoice, { desc = 'Cycle snippet choice', silent = true })
  vim.keymap.set('n', '<leader>fs', function() snacks.picker.snippets() end, { desc = 'Snippet picker' })
  vim.keymap.set('i', '<C-v>', function() snacks.picker.snippets() end, { desc = 'Snippet picker (insert mode)' })
end

function M.setup99()
  vim.keymap.set('n', '<leader>9f', function() require('99').fill_in_function() end, { desc = '99: Fill function' })
  vim.keymap.set('v', '<leader>9v', function() require('99').visual() end, { desc = '99: Visual AI' })
  vim.keymap.set('n', '<leader>9s', function() require('99').stop_all_requests() end, { desc = '99: Stop requests' })
end

function M.setupDiagnosticsQf(event)
  vim.keymap.set('n', '<CR>', '<CR>', { buffer = event.buf, desc = 'Jump to diagnostic', silent = true })
  vim.keymap.set('n', 'q', '<cmd>lclose<CR>', { buffer = event.buf, desc = 'Close diagnostic list', silent = true })
  vim.keymap.set('n', 'p', '<CR><C-w>p', { buffer = event.buf, desc = 'Preview diagnostic', silent = true })
end

return M
